routes/web.php
<?php
use App\Http\Controllers\KontenVideoController;
use App\Http\Controllers\KontenDokumenController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\MataKuliahController;
use App\Http\Controllers\IklanController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\JobChannelController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\AssignmentController;
use App\Http\Controllers\UserAssignmentController;
// use App\Http\Controllers\AssignmentFileController;
// use App\Http\Controllers\AssignmentPilganController;
// use App\Http\Controllers\AssignmentTextController;
use App\Http\Controllers\AksesKelasMahasiswaController;
use App\Http\Controllers\AksesKelasDosenController;
use App\Http\Controllers\API\QuizController;
use App\Http\Controllers\DashboardController;
use App\Models\AssignmentPilgan;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PertemuanController;
use App\Http\Controllers\QuizController as ControllersQuizController;
use App\Models\Assignment;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/fe', function () {
    return view('dosen.fe.index');
})->name('dashboard');
Route::get('/fe-file ', function () {
    return view('dosen.fe.file');
})->name('dashboard');
Route::get('/fe-pilgan ', function () {
    return view('dosen.fe.pilgan');
})->name('dashboard');
// Route::get('/lihat-pertemuan', function () {
//     return view('admin.pertemuan.index');
// })->name('dashboard');
Route::get('/fe-text', function () {
    return view('dosen.fe.text');
})->name('dashboard');
Route::get('/lihat-assignment', function () {
    return view('admin.assignment.lihat');
})->name('dashboard');


Route::get('/', [AuthController::class, 'showFormLogin'])->name('login');
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);

// Route::get('/assignemntText/{id}/create', [AssignmentTextController::class, 'tambahAssignmentText'])->name('tambahAssignmentText');
// Route::post('/assignmentText/store', [AssignmentTextController::class, 'storeAssignmentText'])->name('storeAssignmentText');
// Route::get('/assignmentText/edit/{id}', [AssignmentTextController::class, 'edit'])->name('editAssignmentText');
// Route::post('/assignmentText/update/{id}', [AssignmentTextController::class, 'update'])->name('updateAssignmentText');
// Route::get('/assignmentText/destroy/{id}', [AssignmentTextController::class, 'destroy'])->name('destroyAssignmentText');

// // Route::get('/assignemntFile/{id}/create', [AssignmentFileController::class, 'tambahAssignmentFile'])->name('tambahAssignmentFile');
// // Route::post('/assignmentFile/store', [AssignmentFileController::class, 'storeAssignmentFile'])->name('storeAssignmentFile');
// Route::get('/assignmentFile/edit/{id}', [AssignmentFileController::class, 'edit'])->name('editAssignmentFile');
// Route::post('/assignmentFile/update/{id}', [AssignmentFileController::class, 'update'])->name('updateAssignmentFile');
// Route::get('/assignmentFile/destroy/{id}', [AssignmentFileController::class, 'destroy'])->name('destroyAssignmentFile');

// Route::get('/assignment', [AssignmentPilganController::class, 'index'])->name('assignmentPilgan');
// Route::get('/assignemntPilgan/{id}/create', [AssignmentPilganController::class, 'tambahAssignmentPilgan'])->name('tambahAssignmentPilgan');
// Route::post('/assignmentPilgan/store', [AssignmentPilganController::class, 'storeAssignmentPilgan'])->name('storeAssignmentPilgan');
// Route::get('/assignmentPilgan/edit/{id}', [AssignmentPilganController::class, 'edit'])->name('editAssignmentPilgan');
// Route::post('/assignmentPilgan/update/{id}', [AssignmentPilganController::class, 'update'])->name('updateAssignmentPilgan');
// Route::get('/assignmentPilgan/destroy/{id}', [AssignmentPilganController::class, 'destroy'])->name('destroyAssignmentPilgan');
// Route::get('/assignmentPilgan/{id}/show', [AssignmentPilganController::class, 'show'])->name('showPilgan');
// Route::post('/assignmentPilgan/import', [AssignmentPilganController::class, 'soalPilgan'])->name('soalPilgan');
// Route::get('/Assignment/{id}/assignmentPilgan/data', [AssignmentPilganController::class, 'data'])->name('data');

//Route Assignment File
Route::get('/assignmentFile/{id}/create', [AssignmentController::class, 'viewstoreFile'])->name('viewAssignmentFile');
Route::post('/assignment/store', [AssignmentController::class, 'store'])->name('AssignmentStore');
Route::get('/assignment/destroy/{id}', [AssignmentController::class, 'destroy'])->name('AssignmentDestroy');

//Route Assignment Text
Route::get('/assignmentText/{id}/create', [AssignmentController::class, 'tambahAssignmentText'])->name('tambahAssignmentText');
Route::post('/assignmentText/store', [AssignmentController::class, 'storeAssignmentText'])->name('storeAssignmentText');

//Route Assignment Pilihan Ganda
Route::get('/assignmentPilgan/{id}/create', [AssignmentController::class, 'tambahAssignmentPilgan'])->name('tambahAssignmentPilgan');
Route::post('/assignmentPilgan/store', [AssignmentController::class, 'storeAssignmentPilgan'])->name('storeAssignmentPilgan');
Route::get('/assignmentPilgan/{id}/show', [AssignmentController::class, 'show'])->name('showPilgan');
Route::post('/assignmentPilgan/import', [AssignmentController::class, 'importAssignmentPilgan'])->name('importAssignmentPilgan');
Route::get('/assignmentPilgan/{id}/show', [AssignmentController::class, 'showPilgan'])->name('showPilgan');

Route::post('/pertemuan/store', [PertemuanController::class, 'store'])->name('storePertemuan');
Route::get('/pertemuan/destroy/{id}', [PertemuanController::class, 'destroy'])->name('hapusPertemuan');
Route::get('/pertemuan/lihat-pertemuan/{id}', [PertemuanController::class, 'detail'])->name('detailPertemuan');
Route::get('/tambahKuis/{id}/create', [AssignmentController::class, 'tambahKuis'])->name('tambahKuis');
Route::post('/pertemuan/import', [PertemuanPilganController::class, 'soalQuiz'])->name('soalQuiz');
Route::get('/showAssignment/{id}', [UserAssignmentController::class, 'showAssignment'])->name('showAssignment');

//Quiz
Route::post('/QuizImport', [ControllersQuizController::class,'QuizImport'])->name('QuizImport');
Route::get('/quiz/destroy/{id}', [ControllersQuizController::class, 'destroy'])->name('QuizDestroy');

// Route::get('showKelas/{id)', [KelasController::class, 'show'])->name('showKelas');

//Route Login
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', function () {
        return view('admin.index');
    })->name('dashboard');
    Route::get('/form', function () {
        return view('form');
    })->name('form');
    Route::get('/tab', function () {
        return view('tab');
    })->name('form');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
 
});

Route::resource('kontenVideo', KontenVideoController::class);
Route::resource('kontenDokumen', KontenDokumenController::class);
Route::resource('kelas', KelasController::class);
Route::resource('mataKuliah', MataKuliahController::class);
Route::resource('artikel', ArtikelController::class);
Route::resource('iklan', IklanController::class);
Route::resource('profil', ProfilController::class);
Route::resource('jobChannel', JobChannelController::class);
// Route::resource('assignment', AssignmentController::class);
Route::resource('assignmentFile', AssignmentFileController::class);
//Route::resource('assignmentPilgan', AssignmentPilganController::class);
Route::resource('assignmentText', AssignmentTextController::class);

Route::middleware(['auth', 'role:dosen'])->group(function () {
    Route::get('/dosen', [DashboardController::class, 'dosenDashboard'])
            ->name('dosen.dashboard');
    Route::get('/matkul', function () {
        return view('dosen.assignment.index');
    });
    Route::get('/showMatkul', function () {
        return view('dosen.tugas.tambahTugas');
    });
    Route::get('/showUjian', function () {
        return view('dosen.tugas.tambahUjian');
    });
    Route::get('/show', function () {
        return view('dosen.tugas.show');
    });

    Route::get('/assignment/{id}', [DashboardController::class, 'assignment'])->name('assignment');


    Route::get('/assignment/{id}/show', [DashboardController::class, 'show']);
    Route::get('/assignment/{id}/pilganDetail', [DashboardController::class, 'pilganDetail'])->name('pilganDetail');
    Route::get('/assignment/{id}/textDetail', [DashboardController::class, 'textDetail'])->name('textDetail');
    Route::get('/assignment/{id}/fileDetail', [DashboardController::class, 'fileDetail'])->name('fileDetail');
    Route::get('/showPilgan/{id}', [AssignmentPilganController::class, 'show'])->name('showPilgan');
});

//Role Admin
Route::middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/admin', function () {
        return view('admin.index');
    })->name('admin.dashboard');
    Route::get('/dataDosen', [DashboardController::class, 'dataDosen'])->name('dataDosen');
    Route::get('/dataMahasiswa', [DashboardController::class, 'dataMahasiswa'])->name('dataMahasiswa');
    Route::resource('akseskelasMahasiswa', AksesKelasMahasiswaController::class);
    Route::resource('akseskelasDosen', AksesKelasDosenController::class);
    Route::resource('kategori', KategoriController::class);
});

//Role User

app/Models/Iklan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Iklan extends Model
{
    use HasFactory;
    protected $table = 'iklan';
    protected $fillable = [
        'gambar',
    ];

    
    protected $primaryKey = 'id';
}

app/Http/Controllers/API/IklanController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Iklan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use App\Models\Kelas;

class IklanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index() 
    {
        //return IklanResource::collection(Iklan::all());
        $iklan = Iklan::all();
        return response()->json([
            "message" => "Success",
            "data" => $iklan
        ], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),
              [
                'gambar' => 'required|mimes:jpeg,png,jpg',
             ]);
        if ($validator->fails()) {
            return response()->json(['error'=>$validator->errors()], 401);
        }

        if ($files = $request->file('gambar')) {

            //store file into document folder
            $extention = $request->gambar->extension();
            $file_name = time().'.'.$extention;
            $txt = 'storage/images/'. $file_name;
            $request->gambar->storeAs('public/images', $file_name);

            //store your file into database
            $iklan = new Iklan();
            $iklan->gambar = $file_name;
            $iklan->save();

            return response()->json([
                "success" => true,
                "message" => "Images successfully uploaded",
                "file" => $txt
            ]);

        }
        return Iklan::create($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        return Iklan::find($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $iklan = Iklan::find($id);
        $iklan ->update($request->all());
        return $iklan;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        return Iklan::destroy($id);
    }

    public function download($id)
    {
        $iklan = Iklan::find($id);
        $lst = explode('/', $iklan->gambar);
        $txt = 'api/download_images/'.$lst[2];
        return redirect($txt);
    }

    public function view($id)
    {
        $iklan = Iklan::find($id);
        $lst = explode('/', $iklan->gambar);
        $txt = $iklan->gambar;
        print($txt);
        return redirect($txt);
    }
}

app/Http/Controllers/IklanController.php
<?php

namespace App\Http\Controllers;
use App\Models\Iklan;
use Illuminate\Http\Request;

class IklanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $iklan = Iklan::all();
        return view('admin.iklan.index', compact('iklan'));
    }

    public function create()
    {
     
        return view('admin.iklan.tambah');
    }

    public function store(Request $request)
    {

        $request->validate([
            'gambar' => 'required',
        ]);

        $upload = $request->gambar;
        if (isset($request->gambar)) {
            $extention = $request->gambar->extension();
            $file_name = time() . '.' . $extention;
            $txt = "storage/images/". $file_name;
            $request->gambar->storeAs('public/images', $file_name);
        } else {
            $file_name = null;
        }

        iklan::create([
            'gambar' => $txt,
        ]);
        //notify()->success('Iklan berhasil ditambahkan!');
        return redirect()->route('iklan.index')
            ->with('success', 'Iklan Berhasil Ditambahkan');
    }

    public function show($id)
    {
        $iklans = iklan::where('id', $id)->first();
        return view('admin.iklan.show', compact('iklan'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }


    public function edit($id)
    {
        $iklan = iklan::find($id);

        return view('admin.iklan.edit', compact('iklan'));
    }

    public function update(Request $request, $id)
    {


        $iklan = iklan::findOrFail($id);
        if (isset($request->gambar)){
            $extention = $request->gambar->extension();
            $file_name = time().'.'.$extention;
            $txt = "storage/images/". $file_name;
            $request->gambar->storeAs('public/images', $file_name);
            $iklan->gambar = $txt;
        }else{}

        $iklan->save();
        //notify()->success('Iklan berhasil diedit!');
        return redirect()->route('iklan.index')
        ->with('edit', 'Iklan Berhasil Diedit');
    }

    public function destroy($id)
    {
        iklan::where('id', $id)->delete();
        //notify()->success('Iklan berhasil dihapus');
        return redirect()->route('iklan.index')
        ->with('delete', 'Iklan Berhasil Dihapus');
    }
}

resources/views/admin/iklan/edit.blade.php
<x-app-layout>
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-lg-6 col-12 mx-auto">
        <div class="card card-body mt-4">
          <h6 class="mb-0">Edit Iklan</h6>
          <hr class="horizontal dark my-3">
          <div class="card-body">
            <form role="form text-left" action="{{route('iklan.update',$iklan->id)}}" method="POST" enctype="multipart/form-data">
              @csrf
              @method('PUT')
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Iklan</label> <br>
                <img src="{{ asset( $iklan->gambar) }}" alt=""> <br>
                <input type="file" class="form-control" name="gambar" required>
              </div>
              <div class="text-end">
                      <a href="javascript:history.back()" class="btn bg-gradient-danger"><i class="ni ni-bold-left"></i>&nbsp;&nbsp;Batal</a> 
                <button type="submit" class="btn bg-gradient-dark"><i class="fas fa-plus"></i>&nbsp;&nbsp;Tambah</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</x-app-layout>

resources/views/admin/iklan/index.blade.php
<x-app-layout>
  <div class="col-md-12 mb-lg-0 mb-4">
    <div class="card mt-4">
      <div class="card-header pb-0 p-3">
        <div class="row">
          <div class="col-6 d-flex align-items-center">
            <h6 class="mb-0">Data Iklan</h6>
          </div>
          <div class="col-6 text-end">
            <a class="btn bg-gradient-dark mb-0" href="{{route('iklan.create')}}"><i class="fas fa-plus"></i>&nbsp;&nbsp;Tambah Iklan</a>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="table-responsive">
          <table id="datatable-search" class="table align-items-center mb-0">
            <thead>
              <tr>
                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">No</th>
                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Gambar</th>
                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Aksi</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($iklan as $item)
              <tr>
                <td class="align-middle text-center">
                  <span class="text-secondary text-xs font-weight-bold">{{ $loop->iteration }}</span>
                </td>
                <td class="align-middle text-center ">
                  <div class="position-relative">
                      <img src="{{ asset( $item->gambar) }}" width="100" class="img-fluid shadow border-radius-xl">
                  </div>
                </td>
                <td>
                  <div class="ms-auto text-center">
                    <form action="{{route('iklan.destroy', $item->id)}}" method="POST" style="display: inline">
                      @csrf
                      @method("DELETE")
                      <button type="submit"  class="btn btn-link text-danger text-gradient px-3 mb-0 show_confirm" data-toggle="tooltip" title='Delete'><i class="fas fa-trash text-secondary"></i></button>
                    </form>
                    <a class="btn btn-link text-dark px-3 mb-0" href="{{route('iklan.edit', $item->id)}}"><i class="fas fa-user-edit text-secondary"></i></a>
                  </div>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  @push('scripts')
  <script>
    const dataTableSearch = new simpleDatatables.DataTable("#datatable-search", {
      searchable: true,
      fixedHeight: true
    });

    
    $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Hapus Data?`,
                text: "Jika data terhapus, data akan hilang selamanya!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
              if (willDelete) {
                form.submit();
              }
            });
        });
    
  </script>
  @endpush
</x-app-layout>

resources/views/admin/iklan/tambah.blade.php
<x-app-layout>
  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-lg-6 col-12 mx-auto">
          <div class="card card-body mt-4">
            <h6 class="mb-0">Tambah Data Iklan</h6>
            <hr class="horizontal dark my-3">
            <form role="form text-left" action="{{route('iklan.store')}}" method="POST" enctype="multipart/form-data" id="dropzone">
              @csrf
              <div class="mb-3">
                <label for="exampleFormControlSelect1">Iklan</label>
                <input type="file" class="form-control" name="gambar" required>
              </div>
              <div class="text-end">
                      <a href="javascript:history.back()" class="btn bg-gradient-danger"><i class="ni ni-bold-left"></i>&nbsp;&nbsp;Batal</a> 
                <button type="submit" class="btn bg-gradient-dark"><i class="fas fa-plus"></i>&nbsp;&nbsp;Tambah</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </main>
</x-app-layout>